### PR TITLE
Update vane modes

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Comment by bigmoby** [comment]
Many thanks @drc38 🙌

**Comment by bigmoby** [comment]
Unfortunately, the integrations don't work. The entity is not created and no error log appears.

**Comment by bigmoby** [comment]
@drc38 do you want to give me some fixes before I revert ?

**Comment by drc38** [comment]
#54 reverted my code changes hence why it is not functioning. If you revert #54 and then I expect line 377 may still need deleting depending on whether #55 gets applied.

**Comment by bigmoby** [comment]
Sorry I don't understand

**Comment by drc38** [comment]
The changes from #53 were reverted by #54 so they no longer exist in the code base. Because of this when #55 was applied it only updated the manifest file and `pyfujitsugeneral` to 1.0.11.

If you revert #54 then my changes from #53 will be restored and hopefully #55 will apply the deletion of line 377. If it doesn't it's a simple commit to fix 😉

**Comment by bigmoby** [comment]
oook, I got it now! I'm sorry I merged without analize the code!

**Comment by drc38** [comment]
No problem, will you release v0.2.9?

**Comment by bigmoby** [comment]
Ok, I just tested that and vane position is ok now! Great, good job @drc38 💪
But there's a problem with `operation_mode`.
HA <====> FGLair
cold <--> auto
hot <--> cold
dry <--> dry
fan <--> fan
auto <--> cold

I suppose that alt_heat could affect that.

**Comment by drc38** [comment]
My changes haven't been to anything related to `operation_mode`. I take it you've set `alt_heat` to false?

**Comment by bigmoby** [comment]
Yes, I know with this PR nothing affects `operation_mode`. But in the pyfujitsugeneral library I merged the `alt_heat` feature, which probably causes the issue. I'll try to investigate...that's a problem related with library, not the integration.

**Comment by drc38** [comment]
Strange, can't see how the extra dict entry would affect anything. Let me know what you find out.

**Comment by bigmoby** [comment]
Ok, probably I got it... `operation_mode_desc` maps wrong association!

**Comment by bigmoby** [comment]
2 will be translated into `cool` (wrong)
3 into `auto` (wrong)
4 into `dry` (right)
6 into `heat` (right)
5 into `fan_only` (right)
0 into `off` (right)

**Comment by drc38** [comment]
Just checked on my unit and agree, cool and auto are around the wrong way

**Comment by bigmoby** [comment]
For me this works well 
``` 
    # Translate the operation mode to descriptive values and reverse
    def _operation_mode_translate(self, operation_mode: Any) -> Any:
        DICT_OPERATION_MODE = {
            "off": 0,
            "heat": 6,
            "auto": 2,
            "cool": 3,
            "dry": 4,
            "fan_only": 5,
            "heat_alt": 6,
            0: "off",
            1: "heat",
            2: "auto",
            3: "cool",
            4: "dry",
            5: "fan_only",
            6: "heat",
        }
        return DICT_OPERATION_MODE[operation_mode]
```

So, with my device, ` 1: "heat",` is unuseful

**Comment by drc38** [comment]
If that's the case there is no need for alt_heat, where did the translation to use 1 come from as it wasn't in the original repo? https://github.com/Mmodarre/pyfujitsu

**Comment by bigmoby** [comment]
> If that's the case there is no need for alt_heat, where did the translation to use 1 come from as it wasn't in the original repo? https://github.com/Mmodarre/pyfujitsu

Wow! 😅A git history could give us the truth! Really I don't know why there's 1 for heat! I don't remember that! The next release that will be pruned! 🧹

**Comment by bigmoby** [comment]
Oooops!!! My dramatic fault! 😓
Screenshot 2023-09-23 at 13 54 44

I'll provide to fix, remove and purge ASAP!

**Comment by bigmoby** [comment]
@drc38 please check the current `master` version. I removed `alt_heat` parameter both from the integration and the library.

**Comment by drc38** [comment]
LGTM 👍

**Comment by bigmoby** [comment]
Great, thank you @drc38 ! 🚀

**Pull request merged**
