### PR TITLE
Adjust swing modes

### PR DESCRIPTION
**Pull request by drc38**
@bigmoby here's one approach to support vertical only modes at this stage

### CODE REVIEW

**Comment by drc38** [comment]
@bigmoby this is now working with my unit and the latest update to pyfujitsugeneral, see how it goes with your unit

**Comment by bigmoby** [comment]
Thank you @drc38 🙏

**Comment by bigmoby** [comment]
@drc38 different pyfujitsugeneral library version?
```
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 163, in __init__
    self._swing_modes = self.swing_modes
                        ^^^^^^^^^^^^^^^^
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 377, in swing_modes
    modes_list = self._fujitsu_device.swing_modes()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SplitAC' object has no attribute 'swing_modes'
```

**Comment by drc38** [comment]
@bigmoby the manifest needs to be updated to 1.0.11 ie latest version

**Comment by bigmoby** [comment]
Yes, it's updated to 1.0.11 🤔

**Comment by bigmoby** [comment]
https://github.com/bigmoby/pyfujitsugeneral/blob/master/pyfujitsugeneral/splitAC.py

**Comment by drc38** [comment]
> https://github.com/bigmoby/pyfujitsugeneral/blob/master/pyfujitsugeneral/splitAC.py there's no `swing_modes`

Sorry, missed deleting this line of code from repo when making changes on my local machine. I'll update and re-pull.

**Comment by bigmoby** [comment]
ok no prob thanks 👍

**Comment by bigmoby** [comment]
Unfortunately, the integrations don't work. The entity is not created and no error log appears.

**Pull request merged**
