### PR TITLE
Update climate.py

### PR DESCRIPTION
**Pull request by pbvdven**
i changed the preset boost into aux heat so that you can turn on and off powerful mode

### CODE REVIEW

**Comment by bigmoby** [comment]
Thank you @pbvdven 👍

**Comment by bigmoby** [comment]
Hi @pbvdven why not leave it in the preset menu?

**Comment by pbvdven** [comment]
> Hi @pbvdven why not leave it in the preset menu?

Because you use preset for eco mode on/off 

boost in preset is only (on) there is no (off)

**Comment by bigmoby** [comment]
But as far as I know, boost is a "preset" mode, and the other operation status is the eco mode. It sounds weird to me that the aux heat button could be used as a boost flag. I'm not opinionated about that so I searched in the HA code and, for example, Daikin AC or Hisense or Fibaro integration uses boost as a preset in the preset menu as an alternative to eco. What do you think about that, @pbvdven ? 
Please @chiefcomm what's your point of view about that feature behavior?

**Comment by pbvdven** [comment]
I don't really have an opinion about how its implemented i only want to be able to turn boost off so i added a new one that keeps it in preset as boost but when u select none it turns boost off

**Comment by pbvdven** [comment]
You can place # before line 45 last flag | Support_aux_heat to disable the option.

**Comment by chiefcomm** [comment]
For me the boost in preset is a better fit than aux-heat since boost applies to both cooling and heating, as well boost in FGLair terms is a short term setting which automatically disengages when desired temp is received.   For me aux-heat was never a suitable fit as in Australia we are mostly cooling with occasional heating.

**Comment by bigmoby** [comment]
> For me the boost in preset is a better fit than aux-heat since boost applies to both cooling and heating, as well boost in FGLair terms is a short term setting which automatically disengages when desired temp is received. 

I agree with you, @chiefcomm .
I'm sorry @pbvdven I think it's not the best solution for boost preset functionality :-(

**Comment by pbvdven** [comment]
Like i said i dont have a preference i just want to be able to turn powerful off so then please add powerful mode 0 to preset none so when you select preset none powerful will be turned off as will eco mode.

**Comment by chiefcomm** [comment]
@pbvdven I am confused as to what you are asking.  Powerful setting turns off Eco, Eco turns off Powerful, None turns off both Powerful and Eco.  This is exactly the same as the FGLair mobile app works.  Additionally Powerful mode (boost) is a setting which is automatically turned off by the A/C unit itself once the temperature is reached.

Maybe I am missing something?

Screenshot_20230125-105402 Screenshot_20230125-104929 Screenshot_20230125-105526

**Comment by chiefcomm** [comment]
After more testing I could see to what @pbvdven was referring to, preset none was not disengaging powerful mode.  @bigmoby  PR created to address this issue and have preset none turn off both Eco and Powerful modes.

**Comment by bigmoby** [comment]
Thanks a lot @chiefcomm for your analysis! 👍

**Comment by bigmoby** [comment]
v0.1.9 closes this issue.

**Pull request closed without merging**
